title: Ramaraj's Scribbles
author: Ramaraj T
email: ramaraj.tt@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I write my learnings here so that I can keep this as a note to my future self
  I write about technologies, tips and tricks in mobile development (iOS and Android) here

# social links
twitter_username: ramaraj_tt
github_username: jsramraj

show_excerpts: true # set to false to remove excerpts on the homepage
baseurl: /blogs
theme: jekyll-theme-cayman-blog
# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
#  - jekyll-remote-theme # add this line to the plugins list if you already have one
